### ISSUE TITLE
add Google Analytics

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-www#19]
As an OCW team member, I'd like to be able to see Google Analytics for the site. 

#### Acceptance Criteria:

- [x] Set up appropriate GA accounts for CI, RC and prod
- [x] determine if we should use GA or Google Tag
- [x] set up mechanism to manage the GA/GT account key
- [x] Insert required tags into HTML templates

#### Related issue

- We'll need to configure this in the OCW-course-hugo-theme as well

**Comment by pdpinch** [comment]
I think we can get by with one GA "qa" account for now which we'll use for CI, RC and Prod until we actually launch the next version to users -- at that point we can switch to using the current OCW account, so we have analytics continuity (as much as that's possible).

**Comment by mbertrand** [comment]
Google Tag Manager includes the ability to add Google Analytics tags - and lets you do more than that, like tags for Google Ad Conversion, Facebook Pixel, etc.  Not sure if we'll ever want to do more than that, but the flexibility will be there if we need it.  

So it seems you still need to create (or already have) a Google Analytics account.  Then you create a Google Tag Manager account, set up a tag for Google Analytics, and add the Google Tag Manager javascript to the site instead of the Analytics javascript.  This is a pretty good explanation: https://www.analyticsmania.com/post/google-tag-manager-vs-google-analytics/

Does OCW already have an analytics account that we'd want to keep using for continuity?

**Comment by mbertrand** [comment]
The current OCW site has Google Analytics code as well as publisher tags for Google Ads, for example:
```
googletag.defineSlot('/1064917/HOME_CORP_LOGO_1', [145, 53], 'div-gpt-ad-1388181177156-0').addService(googletag.pubads());
googletag.defineSlot('/1064917/HOME_CORP_LOGO_2', [145, 53], 'div-gpt-ad-1388181177156-1').addService(googletag.pubads());
```

**Comment by pdpinch** [comment]
I'm hoping we can drop the Google Ads support, but I don't know yet -- Does Google Ads benefit at all from the use of Google Tag Manager?

**Comment by mbertrand** [comment]
Google Tag Manager should be able to add google ad conversion tracking code to the page.  But as far as I know, it doesn't support placing ads on the page.  I think that's what at least some of the google ads code on the current OCW page is doing:

<img width="357" alt="Screen Shot 2021-01-25 at 4 20 46 PM" src="https://user-images.githubusercontent.com/187676/105767784-779ce180-5f29-11eb-8ae3-66aebdd51a17.png">

**Comment by mbertrand** [comment]
@pdpinch here's a summary of where I think this issue is now:

- Tentatively decided on using Google Tag Manager
- Created a PR with the necessary JS code for ocw-www.
- There are 3 Google Analytics tracking ids on the legacy site, these could all be added as individual tags to the GTM account.
- There may be 2 GTM accounts affiliated with OCW.  One seems to be called via the Google Ads script on the legacy site, the other is affiliated with one of the analytics accounts.
- Not sure if the current use of Google Ads will be continued on the new site, but that's probably a separate issue anyway.

To do:
- Determine which GTM account should be used for production (ask OCW staff?)
- Add some or all the 3 current analytics tracking ids to that GTM account (Peter? Devops?)
- Create GTM accounts and analytics tracking ids for CI, RC (Devops)
- Assuming this PR is approved, add the GTM code to all the other course pages (ocw-course-hugo-theme)

**Comment by pdpinch** [comment]
@mbertrand what remains to be done here? My current priority is to make sure that we have some tracking set up for ocwnext.odl.mit.edu -- which will have a "sneak preview" in April, but isn't otherwise "production" 

> Determine which GTM account should be used for production (ask OCW staff?)

Don't need this yet. 

> Add some or all the 3 current analytics tracking ids to that GTM account 

I thought this was done. How/Can you confirm?

> Create GTM accounts and analytics tracking ids for CI, RC

I thought this was done also, possibly with one account for both CI & RC

> Assuming this PR is approved, add the GTM code to all the other course pages (ocw-course-hugo-theme)

Is this still an issue?

**Comment by pdpinch** [comment]
Thanks Matt. 

This configuration all _sounds_ right to me, but I'm not seeing any traffic coming through to [OCW Next CI & RC GA](https://analytics.google.com/analytics/web/#/p261658552/realtime/overview?params=_u..nav%3Ddefault) or [OCW Next Prod GA](https://analytics.google.com/analytics/web/#/p261688657/realtime/overview?params=_u..nav%3Ddefault)

Do you know what might be wrong?
