### ISSUE TITLE
Search suggestion is same as search term

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-www#34]
### Steps to Reproduce

Search for "radiative transfer" with a topic of "Particle Physics", i.e. https://ocwnext.odl.mit.edu/search/?q=%22radiative%20transfer%22&t=Particle%20Physics

### Actual Behavior

I get the suggested search message: `Did you mean "radiative transfer"?`

### Expected Behavior

Don't show a "did you mean ...?" suggested search if it's exactly the same as the current search term.

**Comment by aliceriot** [comment]
It seems like this may have something to do with the quotations, not sure. The weird thing is it doesn't happen if you de-select the topic but keep the same search term...

I think this also may be an elasticsearch / backend issue because the same issue happens on the Discussions search, see for instance https://discussions-rc.odl.mit.edu/learn/search?q=%22radiative%20transfer%22&t=Particle%20Physics

It could also be a frontend issue in the shared code between the two, but as I recall the code around showing these suggestions in the UI is very simple, and it basically only shows them when the backend returns them.
