### ISSUE TITLE
Notification banner & about OCW NextGen page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-www#69]
As a OCW admin, I need to add a banner messages to the home page. 

#### Designs & Copy 

InVision mock-up: https://projects.invisionapp.com/d/#/console/18609637/440396978/preview

Draft notification text: "Welcome to the NextGen OCW preview! You can help us make it better by exploring giving us feedback. [Learn More](https://link.to.learn.more/) 

Copy for "Learn More" page: https://docs.google.com/document/d/1FR3-IOhB2iSkQNR7QK7YIpL5ip4GVV3fFiHWGiWOQQU

#### acceptance criteria

- [x] add a generic "Page" content type to `ocw-www`
- [x] add a notifications folder to the site config
- [x] add a markdown page to site content with the content on the banner, including a link to "learn more" 
- [x] render the banner on the home page
- [x] add a markdown page in site content for "about  NextGen OCW"

**Comment by gumaerc** [comment]
@pdpinch @abdulkdawson As you can see above I've created a couple PR's related to this so far.  One adds the ability to create a generic page, and the other adds the notification archetype and the layouts in order to display them.  A couple questions came up in my head while developing this though: 

 - Once a user dismisses a notification we should remember that it was dismissed, correct?  My PR puts a unique identifier on each notification and remembers which ones you have dismissed by ID in the user's `localStorage` but I'm not sure if this is the way we want it to function.  With something like the "give now" notification, maybe we want to implement something like this so the `localStorage` key will expire after a time and show it again?  https://www.sohamkamani.com/blog/javascript-localstorage-with-ttl-expiry/
 - Currently, the partial will show only the latest notification (by date) in the `site/content/notifications` folder.  Do we want the ability to show multiple notifications?  Do we want the ability to override the "show the latest one" behavior and force an older one to show instead?

**Comment by pdpinch** [comment]
Yes, the user shouldn't see the notification again once it's dismissed. I don't think we want it to return after a ttl. Have you looked to see how this is handled on xPRO or Bootcamps?

I think it's fine to show the latest, as long as the site admin has a way to update which is the latest -- perhaps by editing the file?

**Comment by gumaerc** [comment]
@pdpinch I took a look at the way it's handled in XPro, and yea I figured that's the way we wanted it to work but I wanted to make sure.  The admin would create a new notification in that case, because then it would create a new markdown file with a new ID (just a stringified Unix timestamp) and people who had previously hidden the old notification would see the new one, since it would be keyed off a different ID.  If you edited the original notification, people who had already hidden that one would not see it.
